### ISSUE TITLE
Test fails under ASAN

### ISSUE THREAD

**Issue by ribasushi** [rurban/Cpanel-JSON-XS#106]
A test committed as part of https://github.com/rurban/Cpanel-JSON-XS/issues/70 is failing to execute under ASAN ( with output very similar to the original issue ).

If this failure is deliberate/expected - the test must be moved to `xt/...` as to not trip up stock `cpan(m)` installations.

Perl is produced on linux via: `perlbrew install -v -j10 --as 5.24.3_asan -Dusethreads -Accflags="-fsanitize=address -g -O2" -Aldflags="-fsanitize=address -g -O2" perl-5.24.3`

```
t/gh70-asan.t ............... =================================================================
==19131==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6040000a7f30 at pc 0x7f961b51b323 bp 0x7ffd1060a5e0 sp 0x7ffd1060a5d8
READ of size 17 at 0x6040000a7f30 thread T0
    #0 0x7f961b51b322 in XS_Cpanel__JSON__XS_new /home/rabbit/.cpanm/work/1521377489.18808/Cpanel-JSON-XS-4.02/XS.xs:3976
    #1 0x60d72c in Perl_pp_entersub /home/rabbit/perl5/perlbrew/build/perl-5.24.3/pp_hot.c:3988
    #2 0x5f5a15 in Perl_runops_standard /home/rabbit/perl5/perlbrew/build/perl-5.24.3/run.c:41
    #3 0x489728 in S_run_body /home/rabbit/perl5/perlbrew/build/perl-5.24.3/perl.c:2478
    #4 0x489728 in perl_run /home/rabbit/perl5/perlbrew/build/perl-5.24.3/perl.c:2406
    #5 0x421b1d in main /home/rabbit/perl5/perlbrew/build/perl-5.24.3/perlmain.c:116
    #6 0x7f961e88cb44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #7 0x4220b4 (/home/rabbit/perl5/perlbrew/perls/5.24.3_asan/bin/perl+0x4220b4)

0x6040000a7f33 is located 0 bytes to the right of 35-byte region [0x6040000a7f10,0x6040000a7f33)
allocated by thread T0 here:
    #0 0x7f961f9de73f in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x5473f)
    #1 0x59d231 in Perl_safesysmalloc /home/rabbit/perl5/perlbrew/build/perl-5.24.3/util.c:153

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/rabbit/.cpanm/work/1521377489.18808/Cpanel-JSON-XS-4.02/XS.xs:3976 XS_Cpanel__JSON__XS_new
Shadow bytes around the buggy address:
  0x0c088000cf90: fa fa 00 00 00 00 00 fa fa fa 00 00 00 00 00 fa
  0x0c088000cfa0: fa fa 00 00 00 00 00 02 fa fa fd fd fd fd fd fd
  0x0c088000cfb0: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
  0x0c088000cfc0: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x0c088000cfd0: fa fa 00 00 00 00 00 00 fa fa fd fd fd fd fd fa
=>0x0c088000cfe0: fa fa 00 00 00 00[03]fa fa fa 00 00 00 00 05 fa
  0x0c088000cff0: fa fa fd fd fd fd fd fd fa fa 00 00 00 00 00 00
  0x0c088000d000: fa fa 00 00 00 00 00 00 fa fa fd fd fd fd fd fd
  0x0c088000d010: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
  0x0c088000d020: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fd
  0x0c088000d030: fa fa 00 00 00 00 00 00 fa fa fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==19131==ABORTING
```

**Comment by rurban** [comment]
On ASAN this should rather fail, I think. If you need it, force install it there.
It's only an artificial error, as the name will never be on a page boundary.

But I'll add some defensive code for perl5 using strlen.

**Comment by rurban** [comment]
I merged your suggestion: move to xt/ to master. It really is better.
Thanks
